FROM php:8.1.17-fpm-alpine

# Enviorement
ENV TZ=America/Sao_Paulo

RUN apk --no-cache add vim tzdata shadow coreutils curl pcre-dev ${PHPIZE_DEPS} \
&& pecl install redis \
&& docker-php-ext-install pdo pdo_mysql \
&& docker-php-ext-enable redis \
&& addgroup -S -g 1000 docker \
&& adduser -S -u 1000 -g docker docker \
&& rm -Rf /var/cache/apk/* \
&& apk del pcre-dev ${PHPIZE_DEPS}

COPY ./php.ini /usr/local/etc/php/php.ini

USER docker:docker